-- NOTE: It might be unclear whether the diagnostics are generated by this plugin
-- or the LSP plugin. To verify, try toggling this plugin on and off while writing incorrect
-- or poorly formatted code (or with bad practices), and observe if the diagnostic
-- messages appear or disappear accordingly.
return {
  "mfussenegger/nvim-lint",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    require("lint").linters_by_ft = {
      ruby = { "rubocop" },
      kotlin = { "ktlint" },
      go = { "revive" },
      zsh = { "shellcheck" },
    }

    vim.api.nvim_create_autocmd({ "BufWritePost", "BufEnter" }, {
      callback = function()
        require("lint").try_lint()
      end,
    })
  end,
}
